### PR TITLE
Added support for uint32_t, uint64_t, int32_t and int64_t

### PR DESCRIPTION
**Pull request by martinwinter-huawei**
Signed-off-by: Martin Winter <martin.winter@huawei.com>

Add support for all HLSL-supported integer datatypes that were missing
- `uint32_t`
- `uint64_t`
- `int32_t`
- `int64_t`

Supersedes #49 with proper support for the data types, including handling the literal suffixes.

### CODE REVIEW

**Comment by martinwinter-huawei** [comment]
Ran testsuite `tests/launch_tests_linux.sh`:
```
FINISHED. Total = 341
PASS = 339 /341
TODO = 2 /341
Missing EC = 0 /341
FAIL = 0 /341
```
which produces the same output as `development` (on `8010ac9f4d212c597ec365be8cbeae431ef02a2b`)

**Review by galibzon — CHANGES_REQUESTED** [review]
Can you please add unit tests. See here for details: https://github.com/o3de/o3de-azslc/wiki/Adding-New-Test-Cases-To-AZSLc

**Comment by jeremyong-az** [comment]
@galibzon Can you suggest specific tests?

I would recommend at least checking that the types work in the context of a struct bound to an SRG constant buffer (reflected sizes are accounted for properly)

**Comment by martinwinter-huawei** [comment]
I added a few test cases, if you have anything more in particular in mind, do let me know.

**Review by galibzon — APPROVED** [review]

**Review by jeremyong-az — APPROVED** [review]

**Pull request merged**
